// Default route

###
GET  http://localhost:5000/

###
GET  http://localhost:5000/api/users
Authorization: token

###
GET  http://localhost:5000/api/users/4


###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "fullName": "Joseph Admin",
    "email": "email@gmail.com",
    "password": "12345678",
    "userType": "admin"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "12345678"
}

###
PUT  http://localhost:5000/api/users/4
Authorization: 
Content-Type: application/json

{
    "fullName": "John Updated",
    "email": "denis@example.com",
    "password": "password3"
}

###
DELETE  http://localhost:5000/api/users/7
Authorization: token


// STATES
###
GET http://localhost:5000/api/states

###
GET http://localhost:5000/api/states/3

### 
POST http://localhost:5000/api/states
Content-Type: application/json
Authorization: token

{
    "stateName": "NeState",
    "stateCode": "NS"
}

### 
PUT  http://localhost:5000/api/states/3
Content-Type: application/json

{
    "stateName": "New State Updated",
    "stateCode": "NS"
}

###
DELETE  http://localhost:5000/api/states/3


// CITIES
###
GET http://localhost:5000/api/cities
Authorization: token

###
GET http://localhost:5000/api/cities/1
Authorization: token


###
POST http://localhost:5000/api/cities
Content-Type: application/json
Authorization: token

{
    "cityName": "New City",
    "stateId": 1
}

###
POST http://localhost:5000/api/auth/password-reset
Content-Type: application/json

{
    "email": "example@gmail.com"
}
###
PUT http://localhost:5000/api/auth/reset/<token>
Content-Type: application/json

{
    "password": "12345678"
}


